# Generated by Django 4.2.7 on 2023-11-18 09:25

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_format', models.CharField(choices=[('markdown', 'Markdown'), ('org', 'Org-mode'), ('latex', 'LaTeX'), ('typst', 'Typst')], default='org', max_length=20)),
                ('md_content', models.TextField(editable=False)),
                ('html_content', models.TextField(editable=False)),
                ('check_todo', models.BooleanField(default=False)),
                ('do_embed', models.BooleanField(default=True)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(editable=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_day', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('css_class', models.CharField(max_length=50, null=True)),
                ('linum', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document')),
            ],
        ),
        pgvector.django.VectorExtension(),
    ]
