# Generated by Django 4.2.7 on 2023-11-06 07:35

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('content_format', models.CharField(choices=[('markdown', 'Markdown'), ('org', 'Org-mode'), ('latex', 'LaTeX'), ('typst', 'Typst')], default='org', max_length=20)),
                ('md_content', models.TextField(editable=False)),
                ('html_content', models.TextField(editable=False)),
                ('embedding', pgvector.django.VectorField(dimensions=1024)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        pgvector.django.VectorExtension(),
    ]
