# Generated by Django 4.2.7 on 2023-11-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='css_class',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='in_day',
        ),
    ]
