# Generated by Django 4.2.7 on 2023-11-08 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_is_deleted_document_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='trashed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 12, 30, 49, 68466, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
