# Generated by Django 4.2.7 on 2023-11-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todoitem_css_class_todoitem_in_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='cleaned_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
