# Generated by Django 4.2.7 on 2023-11-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_document_is_trashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
