# Generated by Django 4.2.7 on 2023-11-16 05:26

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_document_is_trashed_alter_document_trashed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='never_embed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='pinned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
