# Generated by Django 4.2.7 on 2023-11-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_document_never_embed_document_do_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='check_todo',
            field=models.BooleanField(default=False),
        ),
    ]
